Table  {
    id int [pk, increment]
    
}


 users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE,
  discord_id TEXT UNIQUE,
  name TEXT NOT NULL,
  role TEXT CHECK (role IN ('member', 'officer', 'admin')) DEFAULT 'member',
  created_at TIMESTAMPTZ DEFAULT now()
);